- docs/layout/heights/index.html
- docs/themes/border-radius/index.html
- docs/themes/borders/index.html
- docs/typography/font-family/index.html
- package.json
- src/templates/docs/border-radius/index.html
- src/templates/docs/borders/index.html
- src/templates/docs/font-family/index.html
- src/templates/docs/heights/index.html
Also added autoprefixer to dev dependencies since it was missing.
> Fixing broken links

- docs/general/images/index.html
- docs/index.html
- docs/layout/box-sizing/index.html
- docs/layout/clearfix/index.html
- docs/layout/display/index.html
- docs/layout/floats/index.html
- docs/layout/heights/index.html
- docs/layout/max-widths/index.html
- docs/layout/position/index.html
- docs/layout/spacing/index.html
- docs/layout/widths/index.html
- docs/themes/background-size/index.html
- docs/themes/border-radius/index.html
- docs/themes/borders/index.html
- docs/themes/hovers/index.html
- docs/typography/font-family/index.html
- docs/typography/font-weight/index.html
- docs/typography/line-height/index.html
- docs/typography/scale/index.html
- docs/typography/text-align/index.html
- docs/typography/text-decoration/index.html
- docs/typography/text-transform/index.html
- docs/typography/tracking/index.html
- docs/typography/vertical-align/index.html
- docs/typography/white-space/index.html
The "debug" page was referenced relatively
rather than based off of the root.
Related tachyons-css/tachyons#64
> Fix relative debug url

- docs/general/images/index.html
- docs/index.html
- docs/layout/box-sizing/index.html
- docs/layout/clearfix/index.html
- docs/layout/display/index.html
- docs/layout/floats/index.html
- docs/layout/heights/index.html
- docs/layout/max-widths/index.html
- docs/layout/position/index.html
- docs/layout/spacing/index.html
- docs/layout/widths/index.html
- docs/themes/background-size/index.html
- docs/themes/border-radius/index.html
- docs/themes/borders/index.html
- docs/themes/hovers/index.html
- docs/typography/font-family/index.html
- docs/typography/font-weight/index.html
- docs/typography/line-height/index.html
- docs/typography/scale/index.html
- docs/typography/text-align/index.html
- docs/typography/text-decoration/index.html
- docs/typography/text-transform/index.html
- docs/typography/tracking/index.html
- docs/typography/vertical-align/index.html
- docs/typography/white-space/index.html
Reverts tachyons-css/tachyons-css.github.io#3
I forgot the preceding `doc/`.
> Revert "Fix relative debug url"

- docs/general/images/index.html
- docs/index.html
- docs/layout/box-sizing/index.html
- docs/layout/clearfix/index.html
- docs/layout/display/index.html
- docs/layout/floats/index.html
- docs/layout/heights/index.html
- docs/layout/max-widths/index.html
- docs/layout/position/index.html
- docs/layout/spacing/index.html
- docs/layout/widths/index.html
- docs/themes/background-size/index.html
- docs/themes/border-radius/index.html
- docs/themes/borders/index.html
- docs/themes/hovers/index.html
- docs/typography/font-family/index.html
- docs/typography/font-weight/index.html
- docs/typography/line-height/index.html
- docs/typography/scale/index.html
- docs/typography/text-align/index.html
- docs/typography/text-decoration/index.html
- docs/typography/text-transform/index.html
- docs/typography/tracking/index.html
- docs/typography/vertical-align/index.html
- docs/typography/white-space/index.html
- src/templates/nav_docs.html
The "debug" page was referenced relatively
rather than based off of the root.
Related #64
> Ensure the debug page is correctly linked

- docs/general/images/index.html
- docs/index.html
- docs/layout/box-sizing/index.html
- docs/layout/clearfix/index.html
- docs/layout/display/index.html
- docs/layout/floats/index.html
- docs/layout/heights/index.html
- docs/layout/max-widths/index.html
- docs/layout/position/index.html
- docs/layout/spacing/index.html
- docs/layout/widths/index.html
- docs/themes/background-size/index.html
- docs/themes/border-radius/index.html
- docs/themes/borders/index.html
- docs/themes/hovers/index.html
- docs/typography/font-family/index.html
- docs/typography/font-weight/index.html
- docs/typography/line-height/index.html
- docs/typography/scale/index.html
- docs/typography/text-align/index.html
- docs/typography/text-decoration/index.html
- docs/typography/text-transform/index.html
- docs/typography/tracking/index.html
- docs/typography/vertical-align/index.html
- docs/typography/white-space/index.html
- src/templates/nav_docs.html
They are now absolute paths rather than relative
Closes tachyons-css/tachyons#91
> Fix theme section links

- docs/index.html
Just noticed a typo while on the site.
> Fixed typo

- docs/layout/clearfix/index.html
- docs/layout/heights/index.html
- docs/layout/spacing/index.html
- docs/themes/background-size/index.html
- docs/themes/borders/index.html
Regenerating the docs this morning, I found several modules had been updated since the last docs update. I'll have a number of PRs branch off these changes soon. cc @mrmrs
> Update module metadata

- docs/layout/heights/index.html
> Update heights metadata

- package.json
- readme.md
re: https://twitter.com/mrmrs_/status/713434087109890049
> Add @lachlanjc as a contributor

- docs/elements/forms/index.html
The file is currently referencing `_links.css` but I believe the correct file is `_forms.css`
> Forms file referencing _links css file

- docs/elements/images/index.html
- docs/layout/floats/index.html
- src/templates/docs/floats/index.html
- src/templates/docs/images/index.html
Fixing the grammar as done in #55 and #57 (plus fixing a small spelling error) but from the `src` directory and also committing the built docs.
> correcting spelling and fixing grammar via #57 and #55

- index.html
- src/templates/index.html
Hi ! Just a correction of a typo in `index.html` 😄
> Correcting typo

- index.html
> Fix invalid href attribute

- src/components/article-lists/title-preview-author-media-flipped.html
- src/components/article-lists/title-preview-author-media.html
- src/components/articles/photo-essay.html
- src/components/articles/single-column-large-title.html
- src/components/articles/title-text-image.html
- src/components/cards/news-card.html
- src/components/cards/product-card.html
- src/components/cards/profile-card-title-subtitle.html
- src/components/cards/profile-card.html
- src/components/cards/suggested-profile.html
- src/components/collections/albums.html
- src/components/collections/movies.html
- src/components/collections/vinyl.html
- src/components/forms/checkbox-list.html
- src/components/forms/input-text-label.html
- src/components/forms/newsletter-subscription.html
- src/components/forms/password.html
- src/components/forms/textarea-label.html
Mainly just linking up the forms and adding some labels.
> Some improvements for assistive technology users

- components/quotes/left-border/index.html
> Fix typo in index.html

- gallery/index.html
This PR fixes some incorrect markup in the gallery page. I fixed one `href` attribute and updated a few `title` attributes.
> Fix incorrect gallery markup

- src/templates/docs/spacing/index.html
**Typo:** pt0 -> pb0
**Result:**
> Fix class name in source file

- resources/index.html
- src/templates/resources.html
The `<meta name="description">` was the same for Gallery & Resources, so I've updated that in the compiled version & the template component in /src to resolve this. Let me know if you have questions or feel free to change the description to something better.
> Updated the description for Resources

- docs/layout/grid/index.html
- src/templates/docs/grid/index.html
closes #141
contstruct -> construct
variedy -> variety
> Fix typos in layout docs

- components/index.html
- components/recent.html
- docs/table-of-properties/index.html
- gallery/index.html
- index.html
- resources/index.html
Make version mentions consistent in doc files.
> update version mentions to 4.9.0
